// Mocks generated by Mockito 5.4.4 from annotations
// in ecommerce_demo/test/helpers/helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ecommerce_demo/domain/domain.dart' as _i5;
import 'package:ecommerce_demo/infrastructure/data_source/abstractions/order_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderDataSource extends _i1.Mock implements _i3.OrderDataSource {
  MockOrderDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<dynamic>> getOrders() => (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);
}

/// A class which mocks [OrderRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepo extends _i1.Mock implements _i5.OrderRepo {
  MockOrderRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<Exception, List<_i5.OrderEntity>>> getOrders() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<Exception, List<_i5.OrderEntity>>>.value(
                _FakeEither_0<Exception, List<_i5.OrderEntity>>(
          this,
          Invocation.method(
            #getOrders,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<Exception, List<_i5.OrderEntity>>>);
}
